version: 2
updates:
  # Dependencies for Maven
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 15
    ignore:
      - dependency-name: 'helidon-mp'
      versions: ["3.9.9-TEST1"]

  # Dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
