oauthClient:
  redirectUris:
    - http://localhost:8080/oidc/redirect
  applicationType: web

directions: |+2
  Okta configuration written to src/main/resources/application.yaml.

  Add this file to .gitignore or use environment variables. Don't check in your secrets!

  Run this application with:

      mvn package
      java -jar target/helidon.jar
